name: refinenet
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - cudatoolkit=10.1
  - pytorch
  - torchvision
  - pydap
  - tensorboard
  - tqdm
  - cython
  - scikit-learn
  - pillow
  - matplotlib
  - PyYAML
  - pyzmq
  - opencv
