name: pytorch-refinenet
channels:
  - defaults
dependencies:
  - cudatoolkit=10.1
  - pytorch::pytorch
  - pytorch::torchvision
  - conda-forge::pydap
  - conda-forge::tensorboard
  - conda-forge::tqdm
  - cython
  - scikit-learn
  - pillow
  - matplotlib
  - PyYAML
  - pyzmq
  - opencv

