name: pytorch-refinenet
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - cudatoolkit=10.1
  - pytorch==1.4.0
  - torchvision
  - pydap
  - tensorboard
  - tqdm
  - cython
  - scikit-learn
  - pillow
  - matplotlib
  - PyYAML
  - pyzmq
  - opencv

